GET http://localhost:5000/health

###

GET http://localhost:5000/tasks

###

POST http://localhost:5000/tasks
content-type: application/json

{
    "task": "this is a random task that is due",
    "due_date": "27-03-2025 15:30"
}

